### ISSUE TITLE
can not import

### ISSUE THREAD

**Issue by prologueyan-hr** [jkjung-avt/jetson_nano#1]
can not import caffe 
I follow caffe ssd installation。But after make i still can not import caffe

**Comment by jkjung-avt** [comment]
If you want to be able to import caffe from python3 directly, you need to let python3 add `${HOME}/project/ssd-caffe/python` as one of the paths for importing packages.  For example, you could add the following to your ~/.bashrc:

`export PYTHONPATH=${HOME}/project/ssd-caffe/python`

Thanks for pointing this out.  I shall find time to add this into my blog post.

**Comment by prologueyan-hr** [comment]
thanks a lot!
