### ISSUE TITLE
time on install tensorflow 1.15 with jetpack v4.4

### ISSUE THREAD

**Issue by tranmanhdat** [jkjung-avt/jetson_nano#12]
i wonder how much time does it cost for installing tensorflow v1.15 with jetpack v4.4 in jetson nano device?

**Comment by jkjung-avt** [comment]
I use the tensorflow-1.15.2 pip wheel provided by NVIDIA.  Details could be found in my blog post: [JetPack-4.4 for Jetson Nano](https://jkjung-avt.github.io/jetpack-4.4/).

Overall, it took only 20~30 minutes.

**Comment by tranmanhdat** [comment]
thank you for your response, last time i build from source take about 1 day LOL, pip wheel is a good choice.
