### ISSUE TITLE
Could not find any cuda.h matching version '10.0' in any subdirectory

### ISSUE THREAD

**Issue by yzzymt** [jkjung-avt/jetson_nano#15]
Hi.
I was trying to build tensorflow-1.15.0 for Xavier NX. But it said "Could not find any cuda.h matching version '10.0' in any subdirectory".
My NX Jetpack verison is 4.3. It only has CUDA 10.2. I noticed that you have built tensorflow-1.15.0 with Jetpack 4.3. So could you please share more information about how to build tensorflow-1.15.0 with Jetpack 4.3?

**Comment by yzzymt** [comment]
`
Could not find any cuda.h matching version '10.0' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/usr/local/cuda'
Asking for detailed CUDA configuration...

Please specify the locally installed NCCL version you want to use. [Leave empty to use http://github.com/nvidia/nccl]: 


Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: 
`

**Comment by jkjung-avt** [comment]
Please refer to [this announcement](https://forums.developer.nvidia.com/t/jetpack-4-3-l4t-r32-3-1-released/109273).  JetPack-4.3 has CUDA 10.0 Toolkit in it.

I think you are using JetPack-4.4 (CUDA 10.2) on Jetson Xavier NX.  Please refer to my [Setting up Jetson Xavier NX](https://jkjung-avt.github.io/setting-up-xavier-nx/) blog post.  I would suggest you to use the official tensorflow-1.15.2 wheel, instead of building from source.

**Comment by drakkan** [comment]
You can try to build from source TF 2.3.0, it works for me with JetPack-4.4. 

However I think building from source is only useful if you have to run a TF c/c++ application, if you only need to use TF from python the official wheel is the best choice.

**Comment by yzzymt** [comment]
> Please refer to [this announcement](https://forums.developer.nvidia.com/t/jetpack-4-3-l4t-r32-3-1-released/109273). JetPack-4.3 has CUDA 10.0 Toolkit in it.
> 
> I think you are using JetPack-4.4 (CUDA 10.2) on Jetson Xavier NX. Please refer to my [Setting up Jetson Xavier NX](https://jkjung-avt.github.io/setting-up-xavier-nx/) blog post. I would suggest you to use the official tensorflow-1.15.2 wheel, instead of building from source.



> You can try to build from source TF 2.3.0, it works for me with JetPack-4.4.
> 
> However I think building from source is only useful if you have to run a TF c/c++ application, if you only need to use TF from python the official wheel is the best choice.

Thank you guys.
I successfully built latest tensorflow-master with --config=v1
