### ISSUE TITLE
Did you try to install TF2.4 from source with GPU accel on Nano or NX?

### ISSUE THREAD

**Issue by Tetsujinfr** [jkjung-avt/jetson_nano#16]
I am considering installing TF2.4 from source, and I will leverage your script for 2.3 to get there I think.
Not really an issue but I was wondering if you tried it already?
I need TF2.4 nightly installed from source to get TTS fastspeech with TFlight optim to work on the NX, I think. (I get the regular tf model to work on the jetson but not the tflight one due to some operators missing under my TF2.2 current install.

**Comment by jkjung-avt** [comment]
I have not tried building TensorFlow 2.4 myself.  But I definitely think you could use my install_tensorflow-2.3.0.sh as the basis for doing that.
