### ISSUE TITLE
tf2.0, tx2 or xavier and --local_resources

### ISSUE THREAD

**Issue by alexis-gruet-deel** [jkjung-avt/jetson_nano#2]
Thanks for this useful contribution, 

Just to notice ; That should be nice to add a condition for the  --local_resources=x,y,z in the script install_tensorflow-2.0.0.sh according to the target where tf is built

For instance, with the current parameters 2048.0,1.0,1.0 - on a tx2 or xavier, the compilation time can lead to more than 48 hours for the ~21427 targets to build. 

However, with --local_resources=3072,6.0,1.0 the compilation time will drop significantly on a tx2 (if nvpmodel=0) and --local_ressources=4096,16,1.0 for xavier. 

If this is something interesting for the users I can prepare a PR.

**Comment by jkjung-avt** [comment]
Thanks for the suggestion.  I've updated both 'install_tensorflow-2.0.0.sh' and 'install_tensorflow-1.12.2.sh' based on your suggestion.

Previously I did not test the scripts on TX2 and AGX Xavier, so I was not sure what configuration would work.  Thanks again.
