### ISSUE TITLE
Error installing protobuf-3.8.0.sh

### ISSUE THREAD

**Issue by mjack3** [jkjung-avt/jetson_nano#22]
I have a jetson Nano with JetPack 4.5, python 3.6.9 and pip 21.0.1

I was doing this:
$ wget https://github.com/jkjung-avt/jetson_nano/blob/master/install_protobuf-3.8.0.sh
$ sudo chmod +x install_protobuf-3.8.0.sh
$ ./install_protobuf-3.8.0.sh

and got the next error:

./install_protobuf-3.8.0.sh: line 7: syntax error near unexpected token `newline'
./install_protobuf-3.8.0.sh: line 7: `<!DOCTYPE html>'

**Comment by jkjung-avt** [comment]
Please replace the "wget" command with the following (downloading the raw file instead of the GitHub web page):

```
$ wget https://raw.githubusercontent.com/jkjung-avt/jetson_nano/master/install_protobuf-3.8.0.sh
```
