### ISSUE TITLE
Issues during installing TF 1.15

### ISSUE THREAD

**Issue by sachinkmohan** [jkjung-avt/jetson_nano#23]
First of all, wonderful blog and repository. You are a life saver!! 

The install script couldn't successfully complete the build of TF 1.15. However I tried a different solution. 

I changed the below packages in the script with these versions

```
sudo apt-get install -y libhdf5-serial-dev hdf5-tools
sudo pip3 install -U pip six wheel setuptools mock
sudo pip3 install -U 'numpy<1.19.0'
sudo pip3 install -U h5py==2.10.0
sudo pip3 install pandas
sudo pip3 install future
sudo pip3 install -U keras_applications==1.0.8 --no-deps
sudo pip3 install -U keras_preprocessing==1.1.2 --no-deps
```

Plus the patch in the code didn't help me either. I tried without applying the patch after checking out TF branch 1.15 from the TF github repository and it worked.

**Comment by jkjung-avt** [comment]
Thanks for sharing this.  I've only made sure the "install_tensorflow-1.15.0.sh" script worked OK for JetPack-4.2.  It could indeed have problems for newer versions of JetPacks.

I've just updated the script accordingly: [ca4fe35](https://github.com/jkjung-avt/jetson_nano/commit/ca4fe35373b02c36791a2deb14948fdda992eb58).

**Comment by sachinkmohan** [comment]
Oh, okay, no problem! Thanks a lot! I used jetpack 4.3, so that I could use Cuda 10 and cuDNN 7.
