### ISSUE TITLE
jetpack-4.3 upgrade pip3 command not found

### ISSUE THREAD

**Issue by naivelogic** [jkjung-avt/jetson_nano#4]
In https://jkjung-avt.github.io/jetpack-4.3/, section 2. "Making sure python3 ‘cv2’ is working", i got an error: `pip3 command not found`. When i ran `sudo apt-get install python3-pip` it fixed the issue. suggest updated to sudo apt install: `sudo apt-get install -y python3-dev python3-testresources python3-pip`.

Thanks.

**Comment by naivelogic** [comment]
also in 5. Testing TensorRT UFF SSD models on https://jkjung-avt.github.io/jetpack-4.3/, change `$ ./create_engines.sh` to `$ ./build_engines.sh`

**Comment by jkjung-avt** [comment]
Thanks a lot for proof-reading my blog post.  I have correct the post accordingly.
