### ISSUE TITLE
build tensorflow 1.15

### ISSUE THREAD

**Issue by PythonImageDeveloper** [jkjung-avt/jetson_nano#6]
Hi,
As Install Tensorflow-1.15 on jetpack-4.2.2, the **trt_version=$(echo /usr/lib/aarch64-linux-gnu/libnvinfer.so.? | cut -d '.' -f 3)**  in the .sh file, I get version 5, but in that directory, I have both 5,6 version, If I want to use version 6, How do i do?
Is compatible Installing Tensorflow-1.15 with jetpack-4.2.2 and protobuf-3.6.1 and bazel-0.26.1?

**Comment by jkjung-avt** [comment]
Easy.  Just replace that line of script with:

`trt_version=6`

I think protobuf-3.6.1 and bazel-0.26.1 should be OK for tensorflow-1.15.
