### ISSUE TITLE
install opencv_3.4.8 on jetson nano

### ISSUE THREAD

**Issue by PythonImageDeveloper** [jkjung-avt/jetson_nano#7]
Hi,
I installed the opencv_3.4.8 on jetson nano with jetpack-4.3, I get this error:

patching file /usr/local/cuda/include/cuda_gl_interop.h
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored
** Download opencv-3.4.8
** ERROR: opencv-3.4.8 directory already exists

**Comment by jkjung-avt** [comment]
1. The patch file warning could be safely ignored.  It simply means the file is already patched (no need to patch again).

2. "ERROR: opencv-3.4.8 directory already exists".  You could just do the following and run the installation script again.

   `$ rm -rf ${HOME}/src/opencv-3.4.8`

**Comment by PythonImageDeveloper** [comment]
In jetpack-4.3, Is't install opencv4 by default?

**Comment by jkjung-avt** [comment]
Yes.  Please read my blog post: [JetPack-4.3 for Jetson Nano](https://jkjung-avt.github.io/jetpack-4.3/)
